#███████╗███████╗ █████╗ ███╗   ███╗██╗     ███████╗███████╗███████╗
#██╔════╝██╔════╝██╔══██╗████╗ ████║██║     ██╔════╝██╔════╝██╔════╝
#███████╗█████╗  ███████║██╔████╔██║██║     █████╗  ███████╗███████╗
#╚════██║██╔══╝  ██╔══██║██║╚██╔╝██║██║     ██╔══╝  ╚════██║╚════██║
#███████║███████╗██║  ██║██║ ╚═╝ ██║███████╗███████╗███████║███████║
#╚══════╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝╚══════╝

#██╗   ██╗██████╗  ██████╗ ██████╗  █████╗ ██████╗ ███████╗███████╗
#██║   ██║██╔══██╗██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔════╝
#██║   ██║██████╔╝██║  ███╗██████╔╝███████║██║  ██║█████╗  ███████╗
#██║   ██║██╔═══╝ ██║   ██║██╔══██╗██╔══██║██║  ██║██╔══╝  ╚════██║
#╚██████╔╝██║     ╚██████╔╝██║  ██║██║  ██║██████╔╝███████╗███████║
 #╚═════╝ ╚═╝      ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝
#By DroppingAnvil
# Permission: seamlessupgrades.modify (recommended high ranking staff only)
Messages:
  ### Messages and how to use them ###
  # Generic-Edited is the broadest statement possible when a players upgrade is modified
  # Now if you want to get more specific you can add more messages to each message by simply adding the upgrade name with -Edited, -Added, or -Removed
  # Ex. Keep_Inventory-Edited: 'message' or Keep_Inventory-Removed: 'message'
  # Official names available in data.yml
  Generic-Edited: '&8[&4&l&oSF&r&8]&r &8You now have {AMOUNT} {UPGRADE}s'
  Keep_Inventory-Added: '&8[&4&l&oSF&r&8]&r &8You have received a inventory keep temporary upgrade, you now have {AMOUNT}'
  Keep_Inventory-Removed: '&8[&4&l&oSF&r&8]&r &8You have {AMOUNT} keep inventory credits remaining.'
