#███████╗███████╗ █████╗ ███╗   ███╗██╗     ███████╗███████╗███████╗
#██╔════╝██╔════╝██╔══██╗████╗ ████║██║     ██╔════╝██╔════╝██╔════╝
#███████╗█████╗  ███████║██╔████╔██║██║     █████╗  ███████╗███████╗
#╚════██║██╔══╝  ██╔══██║██║╚██╔╝██║██║     ██╔══╝  ╚════██║╚════██║
#███████║███████╗██║  ██║██║ ╚═╝ ██║███████╗███████╗███████║███████║
#╚══════╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝╚══════╝

#██╗   ██╗██████╗  ██████╗ ██████╗  █████╗ ██████╗ ███████╗███████╗
#██║   ██║██╔══██╗██╔════╝ ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔════╝
#██║   ██║██████╔╝██║  ███╗██████╔╝███████║██║  ██║█████╗  ███████╗
#██║   ██║██╔═══╝ ██║   ██║██╔══██╗██╔══██║██║  ██║██╔══╝  ╚════██║
#╚██████╔╝██║     ╚██████╔╝██║  ██║██║  ██║██████╔╝███████╗███████║
 #╚═════╝ ╚═╝      ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝
#By DroppingAnvil
# Permission: seamlessupgrades.modify (recommended high ranking staff only)
Messages:
  Generic-Edited: '&8[&4&l&oSF&r&8]&r &8You now have {AMOUNT} {UPGRADE}s'
  Keep_Inventory-Added: '&8[&4&l&oSF&r&8]&r &8You have received a keep inventory credit, you now have {AMOUNT}'
  Keep_Inventory-Removed: '&8[&4&l&oSF&r&8]&r &8You have {AMOUNT} keep inventory credits remaining.'
